name: Latest Blog Posts Workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 0 * * *' # Runs at the end of each day
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
jobs:
  update-readme-with-blog:
    name: Update this repo with new blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "BLOG_FEED"
          template: "<a href=\"$link\"> $title </a><br/><b> $description </b><br/>" 
          feed_list: "https://kerkday.com/feed.xml"
